### ISSUE TITLE
Activate repo discussions

### ISSUE THREAD

**Issue by lordratner** [andyboeh/esphome-sense-u#4]
I'm not entirely proficient in github, but a lot of other repos have a discussion section. If you're interested, could you activate that so we can keep future ideas out of the issues section?

Right now I'm prototyping a box that will be next to the crib. It has an RGB LED and a button. The LED indicates the connection status of the program to the sense-u, and right now the button toggles the power switch. Idea being that when you put the baby in the crib and attach the sense-u, just push the button next to the crib and wait for the green light and you'll know the sense-u is functioning. And when it's time to change a diaper or a leave, push the button and it turns off the connection and the LED. I also have it set up to be red when the connection is bad.

I might add a buzzer to the box for if any of the alarms go off, though. The primary method would be for home assistant automations to deal with the alerting. But if for some reason the Wi-Fi connection goes bad, the buzzer would allow for a last resort alert that the sense-u detects a problem.

I'll move this to the discussion area if you decide you want to activate that.

**Comment by andyboeh** [comment]
I don't use github much either, in the past, I've only used the Wiki for such things. I'll see what I can come up with.

Yeah, I have a similar thing in mind. For the time being, I use a fitness tracker but I would like to have some visual and acoustical feedback as well.
The new base station has an ESP32 inside, but I ordered a used 2nd-generation unit in the hope that it has an ESP32 as well.
